# -*- coding: utf-8 -*-
"""01_Exploracao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwglU5KtKiZ3367hg5Agj0B0mT8yxjGp

**Importando as bibliotecas necessárias e visão geral do dataset**
"""

# Bibliotecas para ajudar na leitura e manipulação de dados
import pandas as pd
import matplotlib.pyplot as plt

# Bibliotecas para ajudar na visualização de dados
import seaborn as sns

"""**Carregando o conjunto de dados**"""

import pandas as pd

df_chamados = pd.read_csv("chamados.csv")

"""**Visualizando as 5 primeiras linhas do conjunto de dados**"""

df_chamados.head()

"""**Verificando a forma (shape) do conjunto de dados**"""

df_chamados.shape

"""*   O conjunto de dados possui 5.000 linhas e 44 colunas.

**Verificando o info()**
"""

df_chamados.info()

"""**Observações**


*   As colunas estão divididas entre variáveis numéricas (int64 e float64) e categóricas/textuais (object).

*   As principais informações dos chamados, como ticket_id, created_at, department, priority, status, assigned_team, resolution_time_hours e target_category, possuem 5.000 valores preenchidos, não apresentando valores ausentes.

*   As variáveis title e description são textuais e podem ser utilizadas posteriormente em análises de texto ou processamento de linguagem natural.

*   As variáveis sentiment_score, num_words, historical_tickets, sla_hours e resolution_time_hours são numéricas e podem ser utilizadas para análises estatísticas.

*   As colunas company, segment, employees, city_y, state_y, contract_type, customer_since, vip e monthly_revenue possuem apenas 2 registros preenchidos de 5.000, indicando uma quantidade extremamente elevada de valores ausentes.

*   As colunas last_event_date, event_types e num_images_y possuem 0 valores preenchidos, ou seja, estão completamente vazias.

*   As colunas relacionadas a eventos, como num_events, num_abertura, num_updates e num_encerramento, possuem dados completos para os 5.000 registros.

*   A variável target_category possui 5.000 registros preenchidos e aparenta ser uma variável importante para o objetivo de classificação do projeto.

**Verificar valores ausentes**
"""

df_chamados.isnull().sum().sort_values(ascending=False)

missing = pd.DataFrame({
    'quantidade': df_chamados.isnull().sum(),
    'percentual': df_chamados.isnull().mean() * 100
})

missing.sort_values('percentual', ascending=False)

"""**Verificar valores duplicados**"""

df_chamados.duplicated().sum()

df_chamados['ticket_id'].duplicated().sum()

df_chamados.dtypes

"""**Conversão das variáveis de data**"""

df_chamados['created_at'] = pd.to_datetime(
    df_chamados['created_at'],
    errors='coerce'
)

df_chamados['created_at'].dtype

df_chamados['created_at'].isna().sum()

errors='coerce'

print("PRIORIDADE:")
print(df_chamados['priority'].value_counts())

print("\nSTATUS:")
print(df_chamados['status'].value_counts())

print("\nDEPARTAMENTO:")
print(df_chamados['department'].value_counts())

print("\nCATEGORIA:")
print(df_chamados['target_category'].value_counts())

print("\ncity_x:")
print(df_chamados['city_x'].value_counts())

print("\ncity_y:")
print(df_chamados['city_y'].value_counts())

print("\nstate_y:")
print(df_chamados['state_y'].value_counts())

print("\nstate_x:")
print(df_chamados['state_x'].value_counts())

print("\nos:")
print(df_chamados['os'].value_counts())

print("\nbrowser:")
print(df_chamados['browser'].value_counts())

print("\ndevice_type:")
print(df_chamados['device_type'].value_counts())

print("\nnetwork_type:")
print(df_chamados['network_type'].value_counts())

"""**Observações — variáveis categóricas**

A análise das variáveis categóricas priority, status, department e target_category não identificou inconsistências aparentes na nomenclatura das categorias. Os valores apresentam padronização de escrita e não foram observadas categorias duplicadas por diferenças de maiúsculas, minúsculas ou grafia.

Também podemos registrar os resultados:

*   Prioridade: Crítica (1.277), Baixa (1.260), Média (1.248) e Alta (1.215).

*   Status: Aberto (1.689), Fechado (1.657) e Em andamento (1.654).

*   Departamento: RH (1.274), TI (1.273), Operações (1.229) e Financeiro (1.224).

*   Categoria: Software (892), Rede (861), Hardware (835), RH (821), Acesso (821) e Financeiro (770).

**Análise estatística das variáveis numéricas**
"""

df_chamados.describe()

"""**Observações — análise estatística**

A análise estatística das variáveis numéricas mostrou que as variáveis historical_tickets, sla_hours e resolution_time_hours apresentam valores dentro de faixas definidas no conjunto de dados. O tempo médio de resolução dos chamados é de aproximadamente 36 horas, enquanto o SLA médio é de aproximadamente 19 horas, indicando a necessidade de investigar o cumprimento dos SLAs. A variável sentiment_score apresenta valores entre -1 e 1, com média próxima de zero. A variável has_attachment apresenta valores binários entre 0 e 1, com aproximadamente metade dos registros indicando a presença de anexos.

Também foi identificado que as variáveis num_events, num_abertura, num_updates e num_encerramento apresentam valor zero em todos os registros, sendo necessária uma investigação antes de utilizá-las ou removê-las. As variáveis employees e monthly_revenue possuem apenas dois valores válidos, enquanto last_event_date, event_types e num_images_y não possuem valores preenchidos.

**Análise do cumprimento do SLA**
"""

df_chamados['sla_estourado'] = (
    df_chamados['resolution_time_hours'] >
    df_chamados['sla_hours']
)

df_chamados['sla_estourado'].value_counts()

df_chamados['sla_estourado'].value_counts(normalize=True) * 100

"""**Análise do SLA por prioridade**"""

sla_prioridade = df_chamados.groupby('priority')['sla_estourado'].agg(
    quantidade='count',
    sla_estourado='sum',
    percentual_estourado='mean'
)

sla_prioridade['percentual_estourado'] *= 100

sla_prioridade

"""A análise do cumprimento do SLA por prioridade mostrou que os percentuais de chamados com SLA estourado são bastante semelhantes entre as categorias. A prioridade Média apresentou o maior percentual, com 73,80%, enquanto a prioridade Crítica apresentou o menor, com 72,98%. A pequena diferença entre as categorias indica que, neste conjunto de dados, a prioridade do chamado não parece produzir uma diferença significativa no cumprimento do SLA.

**Análise do SLA por departamento**
"""

sla_departamento = df_chamados.groupby('department')['sla_estourado'].agg(
    quantidade='count',
    sla_estourado='sum',
    percentual_estourado='mean'
)

sla_departamento['percentual_estourado'] *= 100

sla_departamento

"""A análise do cumprimento do SLA por departamento apresentou resultados bastante semelhantes entre os setores. Financeiro e TI apresentaram as maiores taxas de SLA estourado, ambas de aproximadamente 73,53%, enquanto Operações apresentou a menor taxa, com 72,90%. A pequena diferença entre os departamentos indica que o setor responsável pelo atendimento não apresenta grande variação na taxa de cumprimento do SLA neste conjunto de dados.

**Análise do SLA por categoria**
"""

sla_categoria = df_chamados.groupby('target_category')['sla_estourado'].agg(
    quantidade='count',
    sla_estourado='sum',
    percentual_estourado='mean'
)

sla_categoria['percentual_estourado'] *= 100

sla_categoria.sort_values('percentual_estourado', ascending=False)

"""A análise do cumprimento do SLA por categoria apresentou diferenças entre os tipos de chamados. Hardware apresentou a maior proporção de chamados com SLA estourado, com 74,61%, seguido por Software, com 74,55%. A categoria Acesso apresentou a menor proporção, com 71,13%. A diferença de aproximadamente 3,48 pontos percentuais entre a maior e a menor taxa indica uma variação moderada no cumprimento do SLA entre as categorias."""